### ISSUE TITLE
How to retrieve access token from SCSDKClient

### ISSUE THREAD

**Issue by alexjameslittle** [bbookman/Snapchat-Snap-Kit-DIY-Docs#8]
Trying to gain access to the token received from logging in with snapchat so we can do custom auth on our own server.

**Comment by 7atem328** [comment]
...
Button(action: {
// Snapchat requires the UIImage data type in its API call so this takes the Image() and converts it into something Snapchat will accept
let bundlePath = Bundle.main.path(forResource: "SecretClubLogo", ofType: "png")
let image = UIImage(contentsOfFile: bundlePath!)      
let stickerImage = image!

// sets the image as a Sticker for the Snapchat call
let sticker = SCSDKSnapSticker(stickerImage: stickerImage)

// creates an empty response body to send to Snapchat
let snapContent = SCSDKNoSnapContent()
snapContent.sticker = sticker                    // assigns the sticker to the response body

let snapAPI = SCSDKSnapAPI(content: snapContent) // assigns the API call
snapAPI.startSnapping { error in                 // sends the response body to Snapchat with API call
    if let error = error {
        print(error.localizedDescription)
    } else {
        // success
    }
}
}) {
...
